# Use Vim shortcuts
setw -g mode-keys vi

# ensure home/end keys still work in CLIs.
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# Make `Ctrl+B R` reload the config file
unbind r
bind r source-file ~/.tmux.conf

# Pane split & move
bind-key | split-window -h
bind-key - split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key C-x kill-session

# Set mouse on
set -g mouse on 

set -g default-command /bin/bash
set -g default-shell /bin/bash

